---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: template nginx configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: root
    owner: root
    mode: 0644
  with_items:
    - { src: nginx.conf.j2, dest: /etc/nginx/nginx.conf }
    - { src: load_balancer.conf.j2, dest: /etc/nginx/conf.d/load_balancer.conf }
  notify:
    - reload nginx

- name: start and enable nginx
  service: name=nginx state=started enabled=yes
